sonar.organization=nijatkazimli
sonar.projectKey=nijatkazimli_react-native-opencv-wrapper

sonar.sources=src,android/src/main,ios
sonar.tests=src/__tests__

sonar.exclusions=example/**,lib/**,**/build/**,**/__tests__/**,**/*.d.ts,**/*.gradle
sonar.test.inclusions=src/__tests__/**/*.test.ts

sonar.coverage.exclusions=android/**,ios/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
